soap_test_index:
    pattern:  /
    defaults: { _controller: SoapTestBundle:Default:index }

soap_test_get_name_by_id:
    pattern:  /get_name/{id}/
    defaults: { _controller: SoapTestBundle:Default:index }

soap_test_server:
    pattern:  /soap
    defaults: { _controller: SoapTestBundle:Soap:index }

soap_test_test:
    pattern:  /soap/test/{id}/{length}/{timeOut}/
    defaults: { _controller: SoapTestBundle:Soap:get, id: 1, length: 0, timeOut: 20 }
