soap_test_index:
    pattern:  /
    defaults: { _controller: SoapTestBundle:Default:index }

soap_test_server:
    pattern:  /soap
    defaults: { _controller: SoapTestBundle:Soap:index }

soap_test_test:
    pattern:  /soap/test/{id}/{length}/
    defaults: { _controller: SoapTestBundle:Soap:get, id: 1, length:0 }
