parameters:
#    soap_test.example.class: Soap\TestBundle\Example

services:
#    soap_test.example:
#        class: %soap_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
