parameters:
#    soap_test.example.class: Soap\TestBundle\Example

services:
#    soap_test.example:
#        class: %soap_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    soap_test_bundle.globals:
        class: Soap\TestBundle\Services\Globals
        arguments: [@kernel]

    soap_test_bundle.soapserver:
        class: Soap\TestBundle\SoapServer\Main
        arguments: [@doctrine.orm.entity_manager,@security.encoder_factory,@soap_test_bundle.globals]
